name: Publish Keyri checksum checker to Gradle plugins

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish plugin
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Publish plugin
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ github.event.release.tag_name }}
        env:
          GRADLE_PUBLISH_VERSION: ${{ github.event.release.tag_name }}
